feat: setQuery (refs #42)
posva/vue-router-mock pull request #47
Opened 2021-01-11 16:31 UTC by cexbrayat

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
 Refs #42

2021-01-11 16:32 UTC, cexbrayat commented on __tests__/navigations.spec.ts
> +  it('can wait for an ongoing navigation', async () => {
I took the liberty to unskip this test, as it was passing. Let me know if that needs to be reverted.

2021-01-12 08:35 UTC, posva requested changes

2021-01-12 08:35 UTC, posva commented on __tests__/params.spec.ts
> +describe('Params utils', () => {
Let's also rename the file to partialLocation instead of params


```suggestion
describe('partial location', () => {
```

2021-01-12 08:35 UTC, posva commented on __tests__/params.spec.ts
> +  describe('`setParams`', () => {
Can you remove the backticks here and on the other places, please?

```suggestion
  describe('setParams', () => {
```

2021-01-12 08:35 UTC, posva commented on __tests__/params.spec.ts
> +      expect(spy).toHaveBeenCalledTimes(1)
I'm realizing this one should be 0 in all cases to be consistent with vue router (duplicated navigations) but I don't think I have exposed the logic for it yet so let's keep it this way for the moment

2021-01-12 08:35 UTC, posva commented on __tests__/params.spec.ts
> +      router.setHash('more')
the hash should always start with `#`, let's add it in tests too to be consistent with real scenarios

2021-01-12 08:59 UTC, cexbrayat commented
@posva I amended the PR with your feedback 👍

2021-01-12 09:34 UTC, posva approved these changes
Thanks!

2021-01-12 09:34 UTC, merged